---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app-config
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    # name: flux-system
    name: app-config
  url: ssh://git@github.com/obrin/app-config
  # url: https://github.com/obrin/app-config

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-config
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: app-config
  path: "./base"
  prune: true

---

# Tell Flux which Git repository to write image updates to
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: app-config
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: app-config
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: "./base"
    strategy: Setters