---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./clusters/my-cluster/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: fleet-infra
  targetNamespace: default
