---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sandbox
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./production
  prune: true
  sourceRef:
    kind: GitRepository
    name: sandbox
  targetNamespace: sandbox
  install:
    createNamespace: true
