---
apiVersion: v1
kind: Namespace
metadata:
  name: vela-system
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubevela
  namespace: vela-system
spec:
  interval: 5m0s
  url: https://charts.kubevela.net/core
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  chart:
    spec:
      chart: vela-core
      version: '1.x'
      sourceRef:
        kind: HelmRepository
        name: kubevela
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
